#Putting the seeding data here, just in case
#>>rails db:seed

User.create!({status: "Active", f_name: "John", l_name: "Jones", email: "admin@myquotes.com", admin: true, password: "admin123"})
User.create!({status: "Active", f_name: "Jack", l_name: "Briggs", email: "jbriggs@hotmail.com", admin: false, password: "jack123"})
User.create!({status: "Active", f_name: "Vince", l_name: "Brown", email: "vinceb@myemail.com", admin: false, password: "vince123"})
User.create!({status: "Active", f_name: "John", l_name: "Doe", email: "jdoe1@myemail.com", admin: true, password: "john123"})
User.create!({status: "Suspended", f_name: "Jane", l_name: "Smith", email: "jsmith2@myemail.com", admin: false, password: "smith456"})
User.create!({status: "Banned", f_name: "Michael", l_name: "Johnson", email: "mjohnson3@myemail.com", admin: true, password: "mike789"})
User.create!({status: "Active", f_name: "Emily", l_name: "Brown", email: "ebrown4@myemail.com", admin: false, password: "emily123"})
User.create!({status: "Suspended", f_name: "Daniel", l_name: "Wilson", email: "dwilson5@myemail.com", admin: true, password: "dan456"})
User.create!({status: "Banned", f_name: "Sarah", l_name: "Miller", email: "smiller6@myemail.com", admin: false, password: "sarah789"})
User.create!({status: "Active", f_name: "Robert", l_name: "Lee", email: "rlee7@myemail.com", admin: true, password: "robert123"})
User.create!({status: "Suspended", f_name: "Jennifer", l_name: "Anderson", email: "janderson8@myemail.com", admin: false, password: "jen456"})
User.create!({status: "Banned", f_name: "William", l_name: "Taylor", email: "wtaylor9@myemail.com", admin: true, password: "william789"})
User.create!({status: "Active", f_name: "Olivia", l_name: "Martinez", email: "omartinez10@myemail.com", admin: false, password: "olivia123"})
User.create!({status: "Active", f_name: "Ethan", l_name: "Davis", email: "edavis11@myemail.com", admin: true, password: "ethan456"})
User.create!({status: "Suspended", f_name: "Ava", l_name: "Garcia", email: "agarcia12@myemail.com", admin: false, password: "ava789"})
User.create!({status: "Banned", f_name: "James", l_name: "Rodriguez", email: "jrodriguez13@myemail.com", admin: true, password: "james123"})
User.create!({status: "Active", f_name: "Mia", l_name: "Perez", email: "mperez14@myemail.com", admin: false, password: "mia456"})
User.create!({status: "Suspended", f_name: "Liam", l_name: "Hernandez", email: "lhernandez15@myemail.com", admin: true, password: "liam789"})
User.create!({status: "Banned", f_name: "Sophia", l_name: "Lopez", email: "slopez16@myemail.com", admin: false, password: "sophia123"})
User.create!({status: "Active", f_name: "Noah", l_name: "Gonzalez", email: "ngonzalez17@myemail.com", admin: true, password: "noah456"})
User.create!({status: "Suspended", f_name: "Emma", l_name: "Clark", email: "eclark18@myemail.com", admin: false, password: "emma789"})
User.create!({status: "Banned", f_name: "Liam", l_name: "Harris", email: "lharris19@myemail.com", admin: true, password: "liam123"})
User.create!({status: "Active", f_name: "Olivia", l_name: "King", email: "oking20@myemail.com", admin: false, password: "olivia456"})

Author.create!({auth_f_name: "Plato", auth_l_name: "of Athens", birth_date: Date.parse('427-01-01'), death_date: Date.parse('347-01-01'), bio: "Ancient Greek philosopher, known for his contributions to ethics, politics, and metaphysics."})
Author.create!({auth_f_name: "Aristotle", auth_l_name: "of Stagira", birth_date: Date.parse('384-01-01'), death_date: Date.parse('322-01-01'), bio: "One of the most influential philosophers in Western thought, contributed to various fields of study."})
Author.create!({auth_f_name: "Immanuel", auth_l_name: "Kant", birth_date: Date.parse('1724-01-01'), death_date: Date.parse('1804-01-01'), bio: "German philosopher known for his works on metaphysics, ethics, and epistemology."})
Author.create!({auth_f_name: "Friedrich", auth_l_name: "Nietzsche", birth_date: Date.parse('1844-01-01'), death_date: Date.parse('1900-01-01'), bio: "German philosopher, famous for his critiques of traditional morality and religion."})
Author.create!({auth_f_name: "Jean-Jacques", auth_l_name: "Rousseau", birth_date: Date.parse('1712-01-01'), death_date: Date.parse('1778-01-01'), bio: "French philosopher, writer, and composer known for his social and political philosophy."})
Author.create!({auth_f_name: "S�ren", auth_l_name: "Kierkegaard", birth_date: Date.parse('1813-01-01'), death_date: Date.parse('1855-01-01'), bio: "Danish philosopher, theologian, and the father of existentialism."})
Author.create!({auth_f_name: "David", auth_l_name: "Hume", birth_date: Date.parse('1711-01-01'), death_date: Date.parse('1776-01-01'), bio: "Scottish philosopher and historian, known for his empiricism and skepticism."})
Author.create!({auth_f_name: "John", auth_l_name: "Locke", birth_date: Date.parse('1632-01-01'), death_date: Date.parse('1704-01-01'), bio: "English philosopher, regarded as one of the most influential Enlightenment thinkers."})
Author.create!({auth_f_name: "Thomas", auth_l_name: "Hobbes", birth_date: Date.parse('1588-01-01'), death_date: Date.parse('1679-01-01'), bio: "English philosopher, known for his work on political philosophy."})
Author.create!({auth_f_name: "Karl", auth_l_name: "Marx", birth_date: Date.parse('1818-01-01'), death_date: Date.parse('1883-01-01'), bio: "German philosopher, economist, and political theorist, famous for Marxism."})
Author.create!({auth_f_name: "Friedrich", auth_l_name: "Engels", birth_date: Date.parse('1820-01-01'), death_date: Date.parse('1895-01-01'), bio: "German philosopher, political theorist, and collaborator of Karl Marx."})
Author.create!({auth_f_name: "Albert", auth_l_name: "Camus", birth_date: Date.parse('1913-01-01'), death_date: Date.parse('1960-01-01'), bio: "French philosopher and writer, known for his work on absurdism and existentialism."})
Author.create!({auth_f_name: "Jean-Paul", auth_l_name: "Sartre", birth_date: Date.parse('1905-01-01'), death_date: Date.parse('1980-01-01'), bio: "French existentialist philosopher, playwright, and novelist."})
Author.create!({auth_f_name: "Baruch", auth_l_name: "Spinoza", birth_date: Date.parse('1632-01-01'), death_date: Date.parse('1677-01-01'), bio: "Dutch philosopher, known for his work on metaphysics and ethics."})
Author.create!({auth_f_name: "Hannah", auth_l_name: "Arendt", birth_date: Date.parse('1906-01-01'), death_date: Date.parse('1975-01-01'), bio: "German-American philosopher and political theorist, known for her work on totalitarianism and authority."})
Author.create!({auth_f_name: "Rene", auth_l_name: "Descartes", birth_date: Date.parse('1596-01-01'), death_date: Date.parse('1650-01-01'), bio: "French philosopher, mathematician, and writer, known for his famous phrase 'I think, therefore I am.'"})

Quote.create!({quote_text: "The unexamined life is not worth living.", public: true, user_com: "A profound insight into the importance of self-reflection.", pub_date: Date.parse('2022-08-15'), user_id: 1, author_id: 1})
Quote.create!({quote_text: "Knowing yourself is the beginning of all wisdom.", public: true, user_com: "A timeless lesson in self-awareness.", pub_date: Date.parse('2021-11-20'), user_id: 2, author_id: 2})
Quote.create!({quote_text: "In philosophy, it is not the attainment of the goal that matters, it is the things that are met along the way.", public: false, user_com: "Reflects the journey and process of philosophical exploration.", pub_date: Date.parse('2021-12-10'), user_id: 3, author_id: 3})
Quote.create!({quote_text: "The snake which cannot cast its skin has to die. As well the minds which are prevented from changing their opinions; they cease to be mind.", public: true, user_com: "A striking analogy between personal growth and mental flexibility.", pub_date: Date.parse('2022-04-05'), user_id: 4, author_id: 4})
Quote.create!({quote_text: "Man is the measure of all things.", public: true, user_com: "An exploration of subjectivity and relativity.", pub_date: Date.parse('2021-12-18'), user_id: 5, author_id: 5})
Quote.create!({quote_text: "Life can only be understood backward; but it must be lived forwards.", public: false, user_com: "A reflection on the nature of human existence.", pub_date: Date.parse('2021-10-02'), user_id: 6, author_id: 6})
Quote.create!({quote_text: "The only way to deal with fear is to face it head on.", public: true, user_com: "A call to confront one's fears directly.", pub_date: Date.parse('2022-01-14'), user_id: 7, author_id: 7})
Quote.create!({quote_text: "I think, therefore I am.", public: true, user_com: "Descartes' famous philosophical statement.", pub_date: Date.parse('2022-03-25'), user_id: 8, author_id: 8})
Quote.create!({quote_text: "People who know little are usually great talkers, while men who know much say little.", public: true, user_com: "An observation on the relationship between knowledge and humility.", pub_date: Date.parse('2022-02-12'), user_id: 9, author_id: 9})
Quote.create!({quote_text: "All men are by nature equal, made all of the same earth by one Workman; and however we deceive ourselves, as dear to God is the poor peasant as the mighty prince.", public: false, user_com: "An expression of the idea of human equality.", pub_date: Date.parse('2021-10-10'), user_id: 10, author_id: 10})
Quote.create!({quote_text: "Man is born free, and everywhere he is in chains.", public: true, user_com: "A reflection on the concept of freedom and social constraints.", pub_date: Date.parse('2021-08-05'), user_id: 11, author_id: 11})
Quote.create!({quote_text: "The life of man is solitary, poor, nasty, brutish, and short.", public: false, user_com: "An exploration of the harsh realities of human existence.", pub_date: Date.parse('2022-06-28'), user_id: 12, author_id: 12})
Quote.create!({quote_text: "Religion is the opium of the people.", public: true, user_com: "A critical perspective on the role of religion in society.", pub_date: Date.parse('2021-09-15'), user_id: 13, author_id: 13})
Quote.create!({quote_text: "Freedom is what you do with what's been done to you.", public: true, user_com: "An interpretation of the relationship between freedom and experience.", pub_date: Date.parse('2022-01-19'), user_id: 14, author_id: 14})
Quote.create!({quote_text: "We are what we believe we are.", public: false, user_com: "An insight into the power of self-perception.", pub_date: Date.parse('2022-05-08'), user_id: 15, author_id: 15})
Quote.create!({quote_text: "In war, the way is to avoid what is strong and to strike at what is weak.", public: true, user_com: "A strategic approach to conflict.", pub_date: Date.parse('2021-11-30'), user_id: 16, author_id: 16})
Quote.create!({quote_text: "The only true wisdom is in knowing you know nothing.", public: false, user_com: "An acknowledgment of the limitations of human knowledge.", pub_date: Date.parse('2022-07-10'), user_id: 17, author_id: 17})
Quote.create!({quote_text: "The unexamined life is not worth living.", public: true, user_com: "A profound insight into the importance of self-reflection.", pub_date: Date.parse('2022-08-15'), user_id: 18, author_id: 18})
Quote.create!({quote_text: "Knowing yourself is the beginning of all wisdom.", public: true, user_com: "A timeless lesson in self-awareness.", pub_date: Date.parse('2021-11-20'), user_id: 19, author_id: 19})
Quote.create!({quote_text: "In philosophy, it is not the attainment of the goal that matters, it is the things that are met along the way.", public: false, user_com: "Reflects the journey and process of philosophical exploration.", pub_date: Date.parse('2021-12-10'), user_id: 20, author_id: 20})
Quote.create!({quote_text: "The snake which cannot cast its skin has to die. As well the minds which are prevented from changing their opinions; they cease to be mind.", public: true, user_com: "A striking analogy between personal growth and mental flexibility.", pub_date: Date.parse('2022-04-05'), user_id: 1, author_id: 1})
Quote.create!({quote_text: "Man is the measure of all things.", public: true, user_com: "An exploration of subjectivity and relativity.", pub_date: Date.parse('2021-12-18'), user_id: 2, author_id: 2})
Quote.create!({quote_text: "Life can only be understood backward; but it must be lived forwards.", public: false, user_com: "A reflection on the nature of human existence.", pub_date: Date.parse('2021-10-02'), user_id: 3, author_id: 3})
Quote.create!({quote_text: "The only way to deal with fear is to face it head on.", public: true, user_com: "A call to confront one's fears directly.", pub_date: Date.parse('2022-01-14'), user_id: 4, author_id: 4})
Quote.create!({quote_text: "I think, therefore I am.", public: true, user_com: "Descartes' famous philosophical statement.", pub_date: Date.parse('2022-03-25'), user_id: 5, author_id: 5})
Quote.create!({quote_text: "People who know little are usually great talkers, while men who know much say little.", public: true, user_com: "An observation on the relationship between knowledge and humility.", pub_date: Date.parse('2022-02-12'), user_id: 6, author_id: 6})
Quote.create!({quote_text: "All men are by nature equal, made all of the same earth by one Workman; and however we deceive ourselves, as dear to God is the poor peasant as the mighty prince.", public: false, user_com: "An expression of the idea of human equality.", pub_date: Date.parse('2021-10-10'), user_id: 7, author_id: 7})
Quote.create!({quote_text: "Man is born free, and everywhere he is in chains.", public: true, user_com: "A reflection on the concept of freedom and social constraints.", pub_date: Date.parse('2021-08-05'), user_id: 8, author_id: 8})
Quote.create!({quote_text: "The life of man is solitary, poor, nasty, brutish, and short.", public: false, user_com: "An exploration of the harsh realities of human existence.", pub_date: Date.parse('2022-06-28'), user_id: 9, author_id: 9})
Quote.create!({quote_text: "Religion is the opium of the people.", public: true, user_com: "A critical perspective on the role of religion in society.", pub_date: Date.parse('2021-09-15'), user_id: 10, author_id: 10})
Quote.create!({quote_text: "Freedom is what you do with what's been done to you.", public: true, user_com: "An interpretation of the relationship between freedom and experience.", pub_date: Date.parse('2022-01-19'), user_id: 11, author_id: 11})
Quote.create!({quote_text: "We are what we believe we are.", public: false, user_com: "An insight into the power of self-perception.", pub_date: Date.parse('2022-05-08'), user_id: 12, author_id: 12})
Quote.create!({quote_text: "In war, the way is to avoid what is strong and to strike at what is weak.", public: true, user_com: "A strategic approach to conflict.", pub_date: Date.parse('2021-11-30'), user_id: 13, author_id: 13})
Quote.create!({quote_text: "The only true wisdom is in knowing you know nothing.", public: false, user_com: "An acknowledgment of the limitations of human knowledge.", pub_date: Date.parse('2022-07-10'), user_id: 14, author_id: 14})

Category.create!({cat_name: "Self-Reflection"})
Category.create!({cat_name: "Wisdom"})
Category.create!({cat_name: "Philosophical Journey"})
Category.create!({cat_name: "Personal Growth"})
Category.create!({cat_name: "Subjectivity"})
Category.create!({cat_name: "Human Existence"})
Category.create!({cat_name: "Confronting Fears"})
Category.create!({cat_name: "Metaphysics"})
Category.create!({cat_name: "Knowledge and Humility"})
Category.create!({cat_name: "Equality and Freedom"})


QuoteCategory.create!({quote_id: 1, category_id: 1})
QuoteCategory.create!({quote_id: 2, category_id: 2})
QuoteCategory.create!({quote_id: 3, category_id: 3})
QuoteCategory.create!({quote_id: 4, category_id: 4})
QuoteCategory.create!({quote_id: 5, category_id: 5})
QuoteCategory.create!({quote_id: 6, category_id: 6})
QuoteCategory.create!({quote_id: 7, category_id: 7})
QuoteCategory.create!({quote_id: 8, category_id: 8})
QuoteCategory.create!({quote_id: 9, category_id: 9})
QuoteCategory.create!({quote_id: 10, category_id: 10})
QuoteCategory.create!({quote_id: 11, category_id: 1})
QuoteCategory.create!({quote_id: 12, category_id: 2})
QuoteCategory.create!({quote_id: 13, category_id: 3})
QuoteCategory.create!({quote_id: 14, category_id: 4})
QuoteCategory.create!({quote_id: 15, category_id: 5})
QuoteCategory.create!({quote_id: 16, category_id: 6})
QuoteCategory.create!({quote_id: 17, category_id: 7})
QuoteCategory.create!({quote_id: 18, category_id: 8})
QuoteCategory.create!({quote_id: 19, category_id: 9})
QuoteCategory.create!({quote_id: 20, category_id: 10})
 